FROM ruby:3.2.2-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]